# Site settings
title: Alain Osifre - Développeur web en freelance - AOSWEB
url: "https://aos-web.github.io"
baseurl: ""
description: Développeur web en freelance
email: alain.osifre.aosweb@gmail.com
author: Alain Osifre
profile: PROFIL
#twitter_username: John_Grib
github_username: aos-web
linkedin: https://www.linkedin.com/in/alain-osifre-9b120256/
facebook: false
comment-support: utterances
params:
  logo: "assets/images/logo.svg"

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Design
bootstrap:
  assets: true

# Collections
collections:
  tools:
    output: true
    order:
      - css.md
      - php.md
      - sql.md
      - typescript.md
      - javascript.md
      - cakephp.md
      - silex.md
      - codeigniter.md
      - ionic.md
      - angular.md
      - symfony.md
      - zend.md
  competences:
    order:
      - application-web.md
      - application-mobile.md
      - integration.md
      - javascript.md
      - wordpress.md

# Comment Service
disqus:
  id: aos-web
  shortname: aos-web
utterances:
  repo: aos-web.github.io
  issue-term: url
  label: Comment
  branch: master

google_analytics:
  ua: UA-89420952-1

google_adsense:
  client: ca-pub-1909921903209443

timezone: "Europe/Paris"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]

sass:
    sass_dir: _sass
